[package]
name = "meeting-countdown"
description = "Prints out the rest time of a meeting compatible for led-matrix-remote"
version = "0.3.0"
authors = ["EdJoPaTo <meeting-countdown-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[dependencies.clap]
version = "2.33"
features = ["wrap_help"]
