[package]
name = "meeting-countdown"
description = "Prints out the rest time of a meeting compatible for led-matrix-remote"
version = "0.5.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/meeting-countdown"
authors = ["EdJoPaTo <meeting-countdown-rust@edjopato.de>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[build-dependencies]
clap = { version = "3", features = ["cargo"] }
clap_complete = "3"

[dependencies]
chrono = "0.4"
clap = { version = "3", features = ["cargo", "wrap_help"] }

[dev-dependencies]
float_eq = "0.7"
